version: '3'
services:

  click-tracker-dash:
    image: abenelazar/click-tracker-dash:latest
    ports:
      - "3000:3000"
    depends_on:
      - click-tracker-api
    links:
      - "click-tracker-api"
    restart: 'always'
    container_name: click-tracker-dash
  click-tracker-api:
    image: abenelazar/click-tracker-api:latest
    ports:
      - "8722:8722"
    depends_on:
      - db
    links:
      - "db"
    restart: 'always'
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    container_name: click-tracker-api
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./click-tracker-postgres/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
